<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GlossarySubjectsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'en' => 'Physics',
                'fa' => 'فزیک',
                'pa' => 'فزيک',
                'mj' => 'فزیک',
                'no' => 'فزیک',
                'ps' => 'فزيک',
                'sh' => 'فزيک',
                'sw' => 'فزيک',
                'uz' => 'فزيک',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-15 23:05:37',
            ],
            [
                'id' => '2',
                'en' => 'Math',
                'fa' => 'ریاضی',
                'pa' => 'رياضي',
                'mj' => 'ریاضی',
                'no' => 'ریاضی',
                'ps' => 'ریاضی',
                'sh' => 'ریاضے',
                'sw' => 'رياضی',
                'uz' => 'ریاضی',
                'created_at' => '2021-04-16 00:44:21',
                'updated_at' => '2021-04-15 23:12:58',
            ],
            [
                'id' => '3',
                'en' => 'Chemistry',
                'fa' => 'کیمیا',
                'pa' => 'کیمیا',
                'mj' => 'کیمیا',
                'no' => 'کیمیا',
                'ps' => 'کيميا',
                'sh' => 'کیمیا',
                'sw' => 'کيميا',
                'uz' => 'کیمیا',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-15 23:42:09',
            ],
            [
                'id' => '4',
                'en' => 'Information technology',
                'fa' => 'فن آوری معلوماتی',
                'pa' => 'فن آوری معلوماتی',
                'mj' => 'فن آوری معلوماتی',
                'no' => 'معلومات تکنالوژی',
                'ps' => 'فن آوری معلوماتی',
                'sh' => 'معلوماتے تکنالوجے',
                'sw' => 'تکنُالوجُا معلومُات',
                'uz' => 'فن آوری معلوماتی',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-16 00:14:13',
            ],
            [
                'id' => '5',
                'en' => 'Biology',
                'fa' => 'بیولوژی',
                'pa' => 'بیولوژی',
                'mj' => 'بیولوژی',
                'no' => 'بیولوژی',
                'ps' => 'بیولوژی',
                'sh' => 'بیولوژی',
                'sw' => 'بیولوژی',
                'uz' => 'بیولوژی',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-15 23:56:19',
            ],
            [
                'id' => '6',
                'en' => 'Agriculture',
                'fa' => 'زراعت',
                'pa' => 'ھټني',
                'mj' => 'زراعت',
                'no' => 'زراعت',
                'ps' => 'کرنه',
                'sh' => 'کښت',
                'sw' => 'رياضی',
                'uz' => 'زراعت',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-15 23:57:43',
            ],
            [
                'id' => '7',
                'en' => 'Sociology',
                'fa' => 'جامعه‌شناسی',
                'pa' => 'جامعه‌شناسی',
                'mj' => 'جامعه‌شناسی',
                'no' => 'جامعه‌شناسی',
                'ps' => 'جامعه‌شناسی',
                'sh' => 'جامعه‌شناسی',
                'sw' => 'جامعه‌شناسی',
                'uz' => 'جامعه‌شناسی',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-15 23:58:23',
            ],
            [
                'id' => '8',
                'en' => 'Accounting',
                'fa' => 'Accounting',
                'pa' => 'Accounting',
                'mj' => 'Accounting',
                'no' => 'Accounting',
                'ps' => 'Accounting',
                'sh' => 'Accounting',
                'sw' => 'Accounting',
                'uz' => 'Accounting',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-16 00:04:58',
            ],
            [
                'id' => '9',
                'en' => 'Political science',
                'fa' => 'Political science',
                'pa' => 'Political science',
                'mj' => 'Political science',
                'no' => 'Political science',
                'ps' => 'Political science',
                'sh' => 'Political science',
                'sw' => 'Political science',
                'uz' => 'Political science',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-16 00:04:43',
            ],
            [
                'id' => '10',
                'en' => 'Literature',
                'fa' => 'Literature',
                'pa' => 'Literature',
                'mj' => 'Literature',
                'no' => 'Literature',
                'ps' => 'Literature',
                'sh' => 'Literature',
                'sw' => 'Literature',
                'uz' => 'Literature',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-16 00:04:30',
            ],
            [
                'id' => '11',
                'en' => 'Arts',
                'fa' => 'Arts',
                'pa' => 'Arts',
                'mj' => 'Arts',
                'no' => 'Arts',
                'ps' => 'Arts',
                'sh' => 'Arts',
                'sw' => 'Arts',
                'uz' => 'Arts',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-16 00:04:18',
            ],
            [
                'id' => '12',
                'en' => 'Music',
                'fa' => 'Music',
                'pa' => 'Music',
                'mj' => 'Music',
                'no' => 'Music',
                'ps' => 'Music',
                'sh' => 'Music',
                'sw' => 'Music',
                'uz' => 'Music',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-16 00:04:08',
            ],
            [
                'id' => '13',
                'en' => 'Food nutrition',
                'fa' => 'Food nutrition',
                'pa' => 'Food nutrition',
                'mj' => 'Food nutrition',
                'no' => 'Food nutrition',
                'ps' => 'Food nutrition',
                'sh' => 'Food nutrition',
                'sw' => 'Food nutrition',
                'uz' => 'Food nutrition',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-16 00:03:55',
            ],
            [
                'id' => '14',
                'en' => 'Health',
                'fa' => 'Health',
                'pa' => 'Health',
                'mj' => 'Health',
                'no' => 'Health',
                'ps' => 'Health',
                'sh' => 'Health',
                'sw' => 'Health',
                'uz' => 'Health',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-16 00:03:43',
            ],
            [
                'id' => '15',
                'en' => 'Economics',
                'fa' => 'Economics',
                'pa' => 'Economics',
                'mj' => 'Economics',
                'no' => 'Economics',
                'ps' => 'Economics',
                'sh' => 'Economics',
                'sw' => 'Economics',
                'uz' => 'Economics',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-16 00:02:55',
            ],
            [
                'id' => '16',
                'en' => 'Law',
                'fa' => 'Law',
                'pa' => 'Law',
                'mj' => 'Law',
                'no' => 'Law',
                'ps' => 'Law',
                'sh' => 'Law',
                'sw' => 'Law',
                'uz' => 'Law',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-16 00:02:43',
            ],
            [
                'id' => '17',
                'en' => 'Language',
                'fa' => 'زبان',
                'pa' => 'زبان',
                'mj' => 'زبان',
                'no' => 'وری',
                'ps' => 'زبان',
                'sh' => 'زبان',
                'sw' => 'زبان',
                'uz' => 'زبان این منبع',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-16 00:01:04',
            ],
            [
                'id' => '18',
                'en' => 'Education',
                'fa' => 'Education',
                'pa' => 'Education',
                'mj' => 'Education',
                'no' => 'Education',
                'ps' => 'Education',
                'sh' => 'Education',
                'sw' => 'Education',
                'uz' => 'Education',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-16 00:01:51',
            ],
            [
                'id' => '19',
                'en' => 'Earth science',
                'fa' => 'Earth science',
                'pa' => 'Earth science',
                'mj' => 'Earth science',
                'no' => 'Earth science',
                'ps' => 'Earth science',
                'sh' => 'Earth science',
                'sw' => 'Earth science',
                'uz' => 'Earth science',
                'created_at' => '2021-04-16 00:34:53',
                'updated_at' => '2021-04-16 00:01:39',
            ],
            [
                'id' => '20',
                'en' => 'Business',
                'fa' => 'Business',
                'pa' => 'Business',
                'mj' => 'Business',
                'no' => 'Business',
                'ps' => 'Business',
                'sh' => 'Business',
                'sw' => 'Business',
                'uz' => 'Business',
                'created_at' => '2021-05-16 14:44:14',
                'updated_at' => '2021-05-16 14:44:14',
            ],
        ];

        DB::table('glossary_subjects')->insert($data);
    }
}
