<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '4',
                'title' => 'Log out',
                'location' => 'user-menu',
                'path' => 'user/logout',
                'parent' => '0',
                'language' => 'und',
                'weight' => '10',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '244',
                'title' => 'About',
                'location' => 'main-menu',
                'path' => '<nolink>',
                'parent' => '0',
                'language' => 'en',
                'weight' => '6',
                'tnid' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '280',
                'title' => 'Support the Library',
                'location' => 'bottom-menu',
                'path' => 'page/21',
                'parent' => '0',
                'language' => 'en',
                'weight' => '8',
                'tnid' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '281',
                'title' => 'Education in Afghanistan',
                'location' => 'bottom-menu',
                'path' => 'page/22',
                'parent' => '0',
                'language' => 'en',
                'weight' => '1',
                'tnid' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '972',
                'title' => 'User account',
                'location' => 'user-menu',
                'path' => 'user',
                'parent' => '0',
                'language' => 'und',
                'weight' => '-10',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '978',
                'title' => 'Create new account',
                'location' => 'user-menu',
                'path' => 'user/register',
                'parent' => '972',
                'language' => 'en',
                'weight' => '0',
                'tnid' => '8412',
                'created_at' => now(),
                'updated_at' => '2019-09-20 16:04:23',
            ],
            [
                'id' => '980',
                'title' => 'Log in',
                'location' => 'user-menu',
                'path' => 'user/login',
                'parent' => '972',
                'language' => 'und',
                'weight' => '0',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '983',
                'title' => 'Request new password',
                'location' => 'user-menu',
                'path' => 'user/password',
                'parent' => '972',
                'language' => 'und',
                'weight' => '0',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2278',
                'title' => 'List File Resources',
                'location' => 'menu-translator-menu',
                'path' => 'manage/resource-files ',
                'parent' => '0',
                'language' => 'en',
                'weight' => '-48',
                'tnid' => '205',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2279',
                'title' => 'Add File Resource',
                'location' => 'menu-translator-menu',
                'path' => 'node/add/resourcefile',
                'parent' => '0',
                'language' => 'en',
                'weight' => '-49',
                'tnid' => '196',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2280',
                'title' => 'Translation Help',
                'location' => 'menu-translator-menu',
                'path' => 'node/1267',
                'parent' => '0',
                'language' => 'und',
                'weight' => '-46',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2281',
                'title' => 'له کتابتون سره مرسته',
                'location' => 'bottom-menu',
                'path' => 'page/793',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '8',
                'tnid' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2282',
                'title' => 'کتابخانه را حمایت کنید',
                'location' => 'bottom-menu',
                'path' => 'page/627',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '8',
                'tnid' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2283',
                'title' => 'په افغانستان کې ښوونه او روزنه',
                'location' => 'bottom-menu',
                'path' => 'page/794',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '1',
                'tnid' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2284',
                'title' => 'در مورد معارف افغانستان',
                'location' => 'bottom-menu',
                'path' => 'page/196',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '1',
                'tnid' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2285',
                'title' => 'د درخت دانش کتابتون',
                'location' => 'main-menu',
                'path' => 'node/796',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '6',
                'tnid' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2286',
                'title' => 'معرفی کتابخانهء درخت دانش',
                'location' => 'main-menu',
                'path' => 'node/628',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '6',
                'tnid' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2301',
                'title' => 'The Library',
                'location' => 'menu-translator-menu',
                'path' => 'resources',
                'parent' => '0',
                'language' => 'en',
                'weight' => '-50',
                'tnid' => '204',
                'created_at' => now(),
                'updated_at' => '2019-08-23 03:07:34',
            ],
            [
                'id' => '2653',
                'title' => 'زما حساب',
                'location' => 'user-menu',
                'path' => 'user',
                'parent' => '0',
                'language' => 'en',
                'weight' => '0',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2654',
                'title' => 'My Account',
                'location' => 'user-menu',
                'path' => 'user',
                'parent' => '0',
                'language' => 'en',
                'weight' => '0',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2655',
                'title' => 'له کتابتون څخه وتل',
                'location' => 'user-menu',
                'path' => 'user/logout',
                'parent' => '0',
                'language' => 'en',
                'weight' => '0',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2656',
                'title' => 'خروج از کتابخانه',
                'location' => 'user-menu',
                'path' => 'user/logout',
                'parent' => '0',
                'language' => 'en',
                'weight' => '0',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2657',
                'title' => 'کتابتون',
                'location' => 'menu-translator-menu',
                'path' => 'resources',
                'parent' => '0',
                'language' => 'und',
                'weight' => '-39',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2658',
                'title' => 'کتابخانه',
                'location' => 'menu-translator-menu',
                'path' => 'resources',
                'parent' => '0',
                'language' => 'und',
                'weight' => '-38',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2659',
                'title' => 'د نوي مطلب زیاتول',
                'location' => 'menu-translator-menu',
                'path' => 'node/add/resourcefile',
                'parent' => '0',
                'language' => 'und',
                'weight' => '-43',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2660',
                'title' => 'اضافه کردن مطلب جدید',
                'location' => 'menu-translator-menu',
                'path' => 'node/add/resourcefile',
                'parent' => '0',
                'language' => 'und',
                'weight' => '-45',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2661',
                'title' => 'سرېزه',
                'location' => 'menu-translator-menu',
                'path' => 'manage/resource-files ',
                'parent' => '0',
                'language' => 'und',
                'weight' => '-41',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2662',
                'title' => 'فهرست مطالب',
                'location' => 'menu-translator-menu',
                'path' => 'manage/resource-files ',
                'parent' => '0',
                'language' => 'und',
                'weight' => '-40',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2663',
                'title' => 'د  ژباړې مرسته',
                'location' => 'menu-translator-menu',
                'path' => 'node/1267',
                'parent' => '0',
                'language' => 'und',
                'weight' => '-44',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '2664',
                'title' => 'رهنمای ترجمه مطالب به دری',
                'location' => 'menu-translator-menu',
                'path' => 'node/1267',
                'parent' => '0',
                'language' => 'und',
                'weight' => '-42',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3094',
                'title' => 'Terms of Use',
                'location' => 'footer-menu',
                'path' => 'page/33',
                'parent' => '0',
                'language' => 'en',
                'weight' => '3',
                'tnid' => '49',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3095',
                'title' => 'Disclaimer',
                'location' => 'footer-menu',
                'path' => 'page/35',
                'parent' => '0',
                'language' => 'en',
                'weight' => '2',
                'tnid' => '53',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3096',
                'title' => 'Contact Us',
                'location' => 'footer-menu',
                'path' => 'contact-us',
                'parent' => '0',
                'language' => 'en',
                'weight' => '1',
                'tnid' => '45',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3097',
                'title' => 'Privacy Policy',
                'location' => 'footer-menu',
                'path' => 'page/34',
                'parent' => '0',
                'language' => 'en',
                'weight' => '4',
                'tnid' => '51',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3098',
                'title' => 'Links',
                'location' => 'footer-menu',
                'path' => 'page/812',
                'parent' => '0',
                'language' => 'en',
                'weight' => '5',
                'tnid' => '47',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3099',
                'title' => 'تماس با ما',
                'location' => 'footer-menu',
                'path' => 'contact-us',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '1',
                'tnid' => '45',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3100',
                'title' => 'اړیکې',
                'location' => 'footer-menu',
                'path' => 'contact-us',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '1',
                'tnid' => '45',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3101',
                'title' => 'پیوند ها',
                'location' => 'footer-menu',
                'path' => 'page/816',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '5',
                'tnid' => '47',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3102',
                'title' => 'تړونه',
                'location' => 'footer-menu',
                'path' => 'page/815',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '5',
                'tnid' => '47',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3103',
                'title' => 'شرایط استفاده',
                'location' => 'footer-menu',
                'path' => 'page/1261',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '3',
                'tnid' => '49',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3104',
                'title' => 'د کارونې شرطونه',
                'location' => 'footer-menu',
                'path' => 'page/1314',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '3',
                'tnid' => '49',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3105',
                'title' => 'حفظ اطلاعات خصوصی',
                'location' => 'footer-menu',
                'path' => 'page/1315',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '4',
                'tnid' => '51',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3106',
                'title' => 'د محرمیت تګلاره',
                'location' => 'footer-menu',
                'path' => 'page/1316',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '4',
                'tnid' => '51',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3107',
                'title' => 'یادداشت ضروری',
                'location' => 'footer-menu',
                'path' => 'page/1317',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '2',
                'tnid' => '53',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3108',
                'title' => 'اړين يادښت',
                'location' => 'footer-menu',
                'path' => 'page/1318',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '2',
                'tnid' => '53',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3292',
                'title' => 'Contact Us',
                'location' => 'main-menu',
                'path' => 'node/1262',
                'parent' => '0',
                'language' => 'en',
                'weight' => '6',
                'tnid' => '119',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3293',
                'title' => 'تماس با ما',
                'location' => 'main-menu',
                'path' => 'node/1313',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '6',
                'tnid' => '119',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3294',
                'title' => 'اړیکې',
                'location' => 'main-menu',
                'path' => 'node/1312',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '6',
                'tnid' => '119',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3676',
                'title' => 'Home',
                'location' => 'top-menu',
                'path' => '/',
                'parent' => '0',
                'language' => 'en',
                'weight' => '1',
                'tnid' => '125',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3678',
                'title' => 'کورپاڼه',
                'location' => 'top-menu',
                'path' => '/',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '1',
                'tnid' => '125',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3679',
                'title' => 'خانه',
                'location' => 'top-menu',
                'path' => '/',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '1',
                'tnid' => '125',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3854',
                'title' => 'The Library',
                'location' => 'menu-visitors-menu',
                'path' => 'resources',
                'parent' => '0',
                'language' => 'en',
                'weight' => '-44',
                'tnid' => '201',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3855',
                'title' => 'Submit a Resource',
                'location' => 'top-menu',
                'path' => 'add/resourcefile',
                'parent' => '0',
                'language' => 'en',
                'weight' => '3',
                'tnid' => '131',
                'created_at' => now(),
                'updated_at' => '2020-08-10 12:19:55',
            ],
            [
                'id' => '3856',
                'title' => 'Library Help',
                'location' => 'footer-menu',
                'path' => 'page/1275',
                'parent' => '0',
                'language' => 'en',
                'weight' => '6',
                'tnid' => '8413',
                'created_at' => now(),
                'updated_at' => '2020-02-16 13:26:02',
            ],
            [
                'id' => '3857',
                'title' => 'پیشنهاد مطلب به کتابخانه',
                'location' => 'top-menu',
                'path' => 'add/resourcefile',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '3',
                'tnid' => '131',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '3858',
                'title' => 'کتابتون ته د سرچينو زياتول',
                'location' => 'top-menu',
                'path' => 'add/resourcefile',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '3',
                'tnid' => '131',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '4109',
                'title' => 'News',
                'location' => 'main-menu',
                'path' => 'news',
                'parent' => '0',
                'language' => 'en',
                'weight' => '5',
                'tnid' => '553',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '5462',
                'title' => 'Our Partners',
                'location' => 'bottom-menu',
                'path' => 'page/4128',
                'parent' => '0',
                'language' => 'en',
                'weight' => '10',
                'tnid' => '206',
                'created_at' => now(),
                'updated_at' => '2019-03-31 05:37:36',
            ],
            [
                'id' => '5463',
                'title' => 'Copyright Guidelines',
                'location' => 'menu-visitors-menu',
                'path' => 'node/1986',
                'parent' => '0',
                'language' => 'en',
                'weight' => '-40',
                'tnid' => '202',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6654',
                'title' => 'اضافه کردن مطلب جدید',
                'location' => 'menu-translator-menu',
                'path' => 'node/add/resourcefile',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '0',
                'tnid' => '196',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6655',
                'title' => 'Your Account',
                'location' => 'menu-visitors-menu',
                'path' => 'user',
                'parent' => '0',
                'language' => 'en',
                'weight' => '-50',
                'tnid' => '200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6656',
                'title' => 'Log off',
                'location' => 'menu-visitors-menu',
                'path' => 'user/logout',
                'parent' => '0',
                'language' => 'en',
                'weight' => '-37',
                'tnid' => '203',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6657',
                'title' => 'حساب شما',
                'location' => 'menu-visitors-menu',
                'path' => 'user',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '-49',
                'tnid' => '200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6658',
                'title' => 'ستاسو حساب',
                'location' => 'menu-visitors-menu',
                'path' => 'user',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '-48',
                'tnid' => '200',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6659',
                'title' => 'کتابخانه',
                'location' => 'menu-visitors-menu',
                'path' => 'resources',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '-42',
                'tnid' => '201',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6660',
                'title' => 'کتابتون',
                'location' => 'menu-visitors-menu',
                'path' => 'resources',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '-43',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6661',
                'title' => 'دستورالعمل های حق التألیف',
                'location' => 'menu-visitors-menu',
                'path' => 'node/1986',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '-39',
                'tnid' => '202',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6662',
                'title' => 'د چاپ او حق التألیف لارښود',
                'location' => 'menu-visitors-menu',
                'path' => 'node/1986',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '-38',
                'tnid' => '202',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6663',
                'title' => 'خروج از کتابخانه',
                'location' => 'menu-visitors-menu',
                'path' => 'user/logout',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '0',
                'tnid' => '203',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6664',
                'title' => 'د کتابتون څخه وتون',
                'location' => 'menu-visitors-menu',
                'path' => 'user/logout',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '0',
                'tnid' => '203',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6801',
                'title' => 'اخبار',
                'location' => 'main-menu',
                'path' => 'news',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '5',
                'tnid' => '553',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6802',
                'title' => 'کتابتون',
                'location' => 'menu-translator-menu',
                'path' => 'resources',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '0',
                'tnid' => '204',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6803',
                'title' => 'کتابتون ته د سرچینی زیاتول',
                'location' => 'menu-translator-menu',
                'path' => 'node/add/resourcefile',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '0',
                'tnid' => '196',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6804',
                'title' => 'لست منابع',
                'location' => 'menu-translator-menu',
                'path' => 'manage/resource-files ',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '0',
                'tnid' => '205',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6805',
                'title' => 'د سرچینو لست',
                'location' => 'menu-translator-menu',
                'path' => 'manage/resource-files ',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '0',
                'tnid' => '205',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6806',
                'title' => 'بازنگری عمومی ترجمه',
                'location' => 'menu-translator-menu',
                'path' => 'admin/config/content/translation-overview-manage',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '0',
                'tnid' => '206',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '6807',
                'title' => 'د ترجمی عمومی کتنه',
                'location' => 'menu-translator-menu',
                'path' => 'admin/config/content/translation-overview-manage',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '0',
                'tnid' => '206',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7439',
                'title' => 'FAQs',
                'location' => 'main-menu',
                'path' => 'node/3837',
                'parent' => '244',
                'language' => 'en',
                'weight' => '0',
                'tnid' => '554',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7440',
                'title' => 'The Team',
                'location' => 'bottom-menu',
                'path' => 'page/3838',
                'parent' => '244',
                'language' => 'en',
                'weight' => '3',
                'tnid' => '555',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7443',
                'title' => 'Library Policies',
                'location' => 'main-menu',
                'path' => '<nolink>',
                'parent' => '244',
                'language' => 'en',
                'weight' => '2',
                'tnid' => '556',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7444',
                'title' => 'DDL Collection Policy',
                'location' => 'bottom-menu',
                'path' => 'page/3839',
                'parent' => '7443',
                'language' => 'en',
                'weight' => '4',
                'tnid' => '557',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7445',
                'title' => 'DDL Resource Priorities & Selection Guidelines',
                'location' => 'bottom-menu',
                'path' => 'page/3840',
                'parent' => '7443',
                'language' => 'en',
                'weight' => '5',
                'tnid' => '558',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7446',
                'title' => 'Resource Quality Checklist',
                'location' => 'bottom-menu',
                'path' => 'page/3841',
                'parent' => '7443',
                'language' => 'en',
                'weight' => '6',
                'tnid' => '559',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7447',
                'title' => 'DDL Collection Weeding Guidelines',
                'location' => 'bottom-menu',
                'path' => 'page/3842',
                'parent' => '7443',
                'language' => 'en',
                'weight' => '7',
                'tnid' => '560',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7450',
                'title' => 'سوالات بیشتر پرسیده شده',
                'location' => 'main-menu',
                'path' => 'node/3837',
                'parent' => '2286',
                'language' => 'fa',
                'weight' => '-50',
                'tnid' => '554',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7451',
                'title' => 'نورې پوښتنې هم شوې دي',
                'location' => 'main-menu',
                'path' => 'node/3837',
                'parent' => '2285',
                'language' => 'ps',
                'weight' => '-50',
                'tnid' => '554',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7452',
                'title' => 'گروه کاری',
                'location' => 'bottom-menu',
                'path' => 'page/3838',
                'parent' => '2286',
                'language' => 'fa',
                'weight' => '3',
                'tnid' => '555',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7453',
                'title' => 'ټیم',
                'location' => 'bottom-menu',
                'path' => 'page/3973',
                'parent' => '2285',
                'language' => 'ps',
                'weight' => '3',
                'tnid' => '555',
                'created_at' => now(),
                'updated_at' => '2019-02-03 00:38:52',
            ],
            [
                'id' => '7454',
                'title' => 'پالیسی های کتابخانه',
                'location' => 'main-menu',
                'path' => '<nolink>',
                'parent' => '2286',
                'language' => 'fa',
                'weight' => '-48',
                'tnid' => '556',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7455',
                'title' => 'د کتابتون کړنلاره',
                'location' => 'main-menu',
                'path' => '<nolink>',
                'parent' => '2285',
                'language' => 'ps',
                'weight' => '-48',
                'tnid' => '556',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7456',
                'title' => 'پالیسی کلکسیون',
                'location' => 'bottom-menu',
                'path' => 'page/3968',
                'parent' => '7454',
                'language' => 'fa',
                'weight' => '4',
                'tnid' => '557',
                'created_at' => now(),
                'updated_at' => '2019-01-09 10:48:32',
            ],
            [
                'id' => '7457',
                'title' => ' د راغوڼدولو(کلیکسیون) پالیسي',
                'location' => 'bottom-menu',
                'path' => 'page/3839',
                'parent' => '7455',
                'language' => 'ps',
                'weight' => '4',
                'tnid' => '557',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7458',
                'title' => 'رهنمود انتخاب و اولویت‌های منابع',
                'location' => 'bottom-menu',
                'path' => 'page/3840',
                'parent' => '7454',
                'language' => 'fa',
                'weight' => '5',
                'tnid' => '558',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7459',
                'title' => 'د سرچینو اولویت بندي او د انتخاب معیارونه',
                'location' => 'bottom-menu',
                'path' => 'page/3983',
                'parent' => '7455',
                'language' => 'ps',
                'weight' => '5',
                'tnid' => '558',
                'created_at' => now(),
                'updated_at' => '2019-02-03 00:48:41',
            ],
            [
                'id' => '7460',
                'title' => 'چک‌لیست کیفیت منابع',
                'location' => 'bottom-menu',
                'path' => 'page/3841',
                'parent' => '7454',
                'language' => 'fa',
                'weight' => '6',
                'tnid' => '559',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7461',
                'title' => 'د سرچینو د کیفیت چک لېسټ',
                'location' => 'bottom-menu',
                'path' => 'page/3984',
                'parent' => '7455',
                'language' => 'ps',
                'weight' => '6',
                'tnid' => '559',
                'created_at' => now(),
                'updated_at' => '2019-02-03 00:49:21',
            ],
            [
                'id' => '7462',
                'title' => 'رهنمودهای اصلاح یا حذف منابع از کلکسیون',
                'location' => 'bottom-menu',
                'path' => 'page/3842',
                'parent' => '7454',
                'language' => 'fa',
                'weight' => '7',
                'tnid' => '560',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7463',
                'title' => 'د ټولګې د تصفیې لارښودونه',
                'location' => 'bottom-menu',
                'path' => 'page/3985',
                'parent' => '7455',
                'language' => 'ps',
                'weight' => '7',
                'tnid' => '560',
                'created_at' => now(),
                'updated_at' => '2019-02-03 00:50:55',
            ],
            [
                'id' => '7468',
                'title' => 'About Us',
                'location' => 'bottom-menu',
                'path' => 'page/15',
                'parent' => '244',
                'language' => 'en',
                'weight' => '2',
                'tnid' => '564',
                'created_at' => now(),
                'updated_at' => '2018-12-25 06:26:52',
            ],
            [
                'id' => '7469',
                'title' => 'درباره ما',
                'location' => 'bottom-menu',
                'path' => 'page/628',
                'parent' => '2286',
                'language' => 'fa',
                'weight' => '2',
                'tnid' => '564',
                'created_at' => now(),
                'updated_at' => '2018-12-25 06:27:31',
            ],
            [
                'id' => '7470',
                'title' => 'نورې پوښتنې هم شوې دي',
                'location' => 'bottom-menu',
                'path' => 'page/796',
                'parent' => '2285',
                'language' => 'ps',
                'weight' => '2',
                'tnid' => '564',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '7505',
                'title' => 'خبرونه',
                'location' => 'main-menu',
                'path' => 'news',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '5',
                'tnid' => '553',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8395',
                'title' => 'Darakht-e Danesh Library',
                'location' => 'top-menu',
                'path' => 'en/resources',
                'parent' => '0',
                'language' => 'en',
                'weight' => '2',
                'tnid' => '566',
                'created_at' => now(),
                'updated_at' => '2020-08-10 12:20:07',
            ],
            [
                'id' => '8396',
                'title' => 'کتابخانه',
                'location' => 'top-menu',
                'path' => 'fa/resources',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '2',
                'tnid' => '566',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8397',
                'title' => 'کتابتون',
                'location' => 'top-menu',
                'path' => 'ps/resources',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '2',
                'tnid' => '566',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8398',
                'title' => 'افغانستان معارف بټه تں',
                'location' => 'bottom-menu',
                'path' => 'page/4125',
                'parent' => '0',
                'language' => 'no',
                'weight' => '1',
                'tnid' => '22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8399',
                'title' => 'خانه',
                'location' => 'top-menu',
                'path' => '/',
                'parent' => '0',
                'language' => 'no',
                'weight' => '1',
                'tnid' => '125',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8400',
                'title' => 'کتابخانه',
                'location' => 'top-menu',
                'path' => 'resources',
                'parent' => '0',
                'language' => 'no',
                'weight' => '2',
                'tnid' => '566',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8401',
                'title' => 'پیشنهاد مطلب به کتابخانه',
                'location' => 'top-menu',
                'path' => 'add/resourcefile',
                'parent' => '0',
                'language' => 'no',
                'weight' => '3',
                'tnid' => '131',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8402',
                'title' => 'خانه',
                'location' => 'top-menu',
                'path' => '/',
                'parent' => '0',
                'language' => 'uz',
                'weight' => '1',
                'tnid' => '125',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8403',
                'title' => 'خانه',
                'location' => 'top-menu',
                'path' => '/',
                'parent' => '0',
                'language' => 'sw',
                'weight' => '1',
                'tnid' => '125',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8404',
                'title' => 'خانه',
                'location' => 'top-menu',
                'path' => '/',
                'parent' => '0',
                'language' => 'mj',
                'weight' => '1',
                'tnid' => '125',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8405',
                'title' => 'کتابخانه',
                'location' => 'top-menu',
                'path' => 'resources',
                'parent' => '0',
                'language' => 'uz',
                'weight' => '2',
                'tnid' => '566',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8406',
                'title' => 'کتابخانه',
                'location' => 'top-menu',
                'path' => 'resources',
                'parent' => '0',
                'language' => 'mj',
                'weight' => '2',
                'tnid' => '566',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8407',
                'title' => 'کتابخانه',
                'location' => 'top-menu',
                'path' => 'sh/resources',
                'parent' => '0',
                'language' => 'sw',
                'weight' => '2',
                'tnid' => '566',
                'created_at' => now(),
                'updated_at' => '2020-09-29 20:07:43',
            ],
            [
                'id' => '8408',
                'title' => 'پیشنهاد مطلب به کتابخانه',
                'location' => 'top-menu',
                'path' => 'add/resourcefile',
                'parent' => '0',
                'language' => 'uz',
                'weight' => '3',
                'tnid' => '131',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8409',
                'title' => 'پیشنهاد مطلب به کتابخانه',
                'location' => 'top-menu',
                'path' => 'add/resourcefile',
                'parent' => '0',
                'language' => 'mj',
                'weight' => '3',
                'tnid' => '131',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8410',
                'title' => 'پیشنهاد مطلب به کتابخانه',
                'location' => 'top-menu',
                'path' => 'add/resourcefile',
                'parent' => '0',
                'language' => 'sw',
                'weight' => '3',
                'tnid' => '131',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8411',
                'title' => 'Impact',
                'location' => 'bottom-menu',
                'path' => 'en/impact',
                'parent' => '0',
                'language' => 'en',
                'weight' => '0',
                'tnid' => '8411',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8412',
                'title' => 'اثرگذاری',
                'location' => 'bottom-menu',
                'path' => 'fa/impact',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '0',
                'tnid' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8413',
                'title' => 'اغیزه',
                'location' => 'bottom-menu',
                'path' => 'ps/impact',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '0',
                'tnid' => '8411',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => '8414',
                'title' => 'ایجاد اکاونت',
                'location' => 'user-menu',
                'path' => 'user/register',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '1',
                'tnid' => '8412',
                'created_at' => '2019-09-23 01:02:53',
                'updated_at' => '2019-09-23 01:02:53',
            ],
            [
                'id' => '8415',
                'title' => 'یے سرچښمه تر کتابجید وېذداو',
                'location' => 'top-menu',
                'path' => 'add/resourcefile',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '131',
                'created_at' => '2020-02-15 04:52:27',
                'updated_at' => '2020-02-16 05:24:14',
            ],
            [
                'id' => '8416',
                'title' => 'چید',
                'location' => 'top-menu',
                'path' => '/',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '-1',
                'tnid' => '125',
                'created_at' => '2020-02-16 05:23:05',
                'updated_at' => '2020-09-29 20:37:41',
            ],
            [
                'id' => '8417',
                'title' => 'کتابجید',
                'location' => 'top-menu',
                'path' => 'sh/resources',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '0',
                'tnid' => '566',
                'created_at' => '2020-02-16 05:23:37',
                'updated_at' => '2020-09-29 20:37:37',
            ],
            [
                'id' => '8418',
                'title' => 'مهش قتے رابطه',
                'location' => 'main-menu',
                'path' => 'node/1262',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '119',
                'created_at' => '2020-02-16 13:16:40',
                'updated_at' => '2020-02-16 13:16:40',
            ],
            [
                'id' => '8419',
                'title' => 'مهش باره یند',
                'location' => 'main-menu',
                'path' => '<nolink>',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '18',
                'created_at' => '2020-02-16 13:17:41',
                'updated_at' => '2020-02-16 13:17:41',
            ],
            [
                'id' => '8420',
                'title' => 'تئثیر پتئود',
                'location' => 'bottom-menu',
                'path' => 'en/impact',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '8411',
                'created_at' => '2020-02-16 13:19:03',
                'updated_at' => '2020-02-16 13:19:03',
            ],
            [
                'id' => '8421',
                'title' => 'تعلیم ات تردۈشت تر افغانستان',
                'location' => 'bottom-menu',
                'path' => 'page/22',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '16',
                'created_at' => '2020-02-16 13:19:40',
                'updated_at' => '2020-02-16 13:19:40',
            ],
            [
                'id' => '8422',
                'title' => 'کتابجید کۈمک کنک',
                'location' => 'bottom-menu',
                'path' => 'page/21',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '14',
                'created_at' => '2020-02-16 13:20:14',
                'updated_at' => '2020-02-16 13:20:14',
            ],
            [
                'id' => '8423',
                'title' => 'مهش شریکېن',
                'location' => 'bottom-menu',
                'path' => 'page/4128',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '206',
                'created_at' => '2020-02-16 13:22:27',
                'updated_at' => '2020-02-16 13:22:27',
            ],
            [
                'id' => '8424',
                'title' => 'مهش قتے رابطه',
                'location' => 'footer-menu',
                'path' => 'contact-us',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '45',
                'created_at' => '2020-02-16 13:24:00',
                'updated_at' => '2020-02-16 13:24:00',
            ],
            [
                'id' => '8425',
                'title' => 'دعوا ناکنک',
                'location' => 'footer-menu',
                'path' => 'page/35',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '53',
                'created_at' => '2020-02-16 13:24:35',
                'updated_at' => '2020-02-16 13:24:35',
            ],
            [
                'id' => '8426',
                'title' => 'کارزئښت شرطېن',
                'location' => 'footer-menu',
                'path' => 'page/33',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '49',
                'created_at' => '2020-02-16 13:25:03',
                'updated_at' => '2020-02-16 13:25:03',
            ],
            [
                'id' => '8427',
                'title' => 'محرمیت قایده',
                'location' => 'footer-menu',
                'path' => 'page/34',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '51',
                'created_at' => '2020-02-16 13:25:27',
                'updated_at' => '2020-02-16 13:25:27',
            ],
            [
                'id' => '8428',
                'title' => 'رابطه یېن',
                'location' => 'footer-menu',
                'path' => 'page/812',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '47',
                'created_at' => '2020-02-16 13:25:49',
                'updated_at' => '2020-02-16 13:25:49',
            ],
            [
                'id' => '8429',
                'title' => 'کتابجید کۈمک',
                'location' => 'footer-menu',
                'path' => 'page/1275',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '8413',
                'created_at' => '2020-02-16 13:26:11',
                'updated_at' => '2020-02-16 13:26:11',
            ],
            [
                'id' => '8430',
                'title' => 'کتابجید',
                'location' => 'menu-translator-menu',
                'path' => 'resources',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '204',
                'created_at' => '2020-02-16 13:27:38',
                'updated_at' => '2020-02-16 13:27:38',
            ],
            [
                'id' => '8431',
                'title' => 'کتابجید',
                'location' => 'menu-visitors-menu',
                'path' => 'resources',
                'parent' => '0',
                'language' => 'sh',
                'weight' => '1',
                'tnid' => '201',
                'created_at' => '2020-02-16 13:28:42',
                'updated_at' => '2020-02-16 13:28:42',
            ],
            [
                'id' => '8432',
                'title' => 'تاثير',
                'location' => 'bottom-menu',
                'path' => 'en/impact',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '8411',
                'created_at' => '2020-03-25 22:23:53',
                'updated_at' => '2020-03-25 22:23:53',
            ],
            [
                'id' => '8433',
                'title' => 'افغانستان کوچه موليني',
                'location' => 'bottom-menu',
                'path' => 'page/22',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '16',
                'created_at' => '2020-03-25 22:24:32',
                'updated_at' => '2020-03-25 22:24:32',
            ],
            [
                'id' => '8434',
                'title' => 'کتابخانا پله سمړې',
                'location' => 'bottom-menu',
                'path' => 'page/21',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '14',
                'created_at' => '2020-03-25 22:25:15',
                'updated_at' => '2020-03-25 22:25:15',
            ],
            [
                'id' => '8435',
                'title' => 'اما يارنن/سمړکالي',
                'location' => 'bottom-menu',
                'path' => 'page/4128',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '206',
                'created_at' => '2020-03-25 22:26:05',
                'updated_at' => '2020-03-25 22:26:05',
            ],
            [
                'id' => '8436',
                'title' => 'امه پله هوړان',
                'location' => 'footer-menu',
                'path' => 'contact-us',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '45',
                'created_at' => '2020-03-25 22:26:50',
                'updated_at' => '2020-03-25 22:26:50',
            ],
            [
                'id' => '8437',
                'title' => 'ضروري اوچان',
                'location' => 'footer-menu',
                'path' => 'page/35',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '53',
                'created_at' => '2020-03-25 22:27:22',
                'updated_at' => '2020-03-25 22:27:22',
            ],
            [
                'id' => '8438',
                'title' => 'يتينيس شرطې',
                'location' => 'footer-menu',
                'path' => 'page/33',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '49',
                'created_at' => '2020-03-25 22:27:49',
                'updated_at' => '2020-03-25 22:27:49',
            ],
            [
                'id' => '8439',
                'title' => 'کيولوالي معلومتنا اُصول',
                'location' => 'footer-menu',
                'path' => 'page/34',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '51',
                'created_at' => '2020-03-25 22:28:22',
                'updated_at' => '2020-03-25 22:28:22',
            ],
            [
                'id' => '8440',
                'title' => 'ډِپانې',
                'location' => 'footer-menu',
                'path' => 'page/812',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '47',
                'created_at' => '2020-03-25 22:28:52',
                'updated_at' => '2020-03-25 22:28:52',
            ],
            [
                'id' => '8441',
                'title' => 'کتابخانا بارا سمړني',
                'location' => 'footer-menu',
                'path' => 'page/1275',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '8413',
                'created_at' => '2020-03-25 22:29:18',
                'updated_at' => '2020-03-25 22:29:18',
            ],
            [
                'id' => '8442',
                'title' => 'پچوالي اگتې',
                'location' => 'main-menu',
                'path' => 'news',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '553',
                'created_at' => '2020-03-25 22:30:21',
                'updated_at' => '2020-03-25 22:30:21',
            ],
            [
                'id' => '8443',
                'title' => 'امه پله هوړان',
                'location' => 'main-menu',
                'path' => 'node/1262',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '119',
                'created_at' => '2020-03-25 22:31:03',
                'updated_at' => '2020-03-25 22:31:03',
            ],
            [
                'id' => '8444',
                'title' => 'امه بارا',
                'location' => 'main-menu',
                'path' => '<nolink>',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '18',
                'created_at' => '2020-03-25 22:31:41',
                'updated_at' => '2020-03-25 22:31:41',
            ],
            [
                'id' => '8445',
                'title' => 'کتابخانا',
                'location' => 'menu-translator-menu',
                'path' => 'resources',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '204',
                'created_at' => '2020-03-25 22:33:57',
                'updated_at' => '2020-03-25 22:33:57',
            ],
            [
                'id' => '8446',
                'title' => 'کتابخانا',
                'location' => 'menu-visitors-menu',
                'path' => 'resources',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '201',
                'created_at' => '2020-03-25 22:35:29',
                'updated_at' => '2020-03-25 22:35:29',
            ],
            [
                'id' => '8447',
                'title' => 'گوشينگ',
                'location' => 'top-menu',
                'path' => '/',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '-1',
                'tnid' => '125',
                'created_at' => '2020-03-25 22:36:40',
                'updated_at' => '2020-09-29 20:38:20',
            ],
            [
                'id' => '8448',
                'title' => 'کتابخانا',
                'location' => 'top-menu',
                'path' => 'pa/resources',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '0',
                'tnid' => '566',
                'created_at' => '2020-03-25 22:37:02',
                'updated_at' => '2020-09-29 20:38:23',
            ],
            [
                'id' => '8449',
                'title' => 'کتابخانايکه  شِراونچنا شريني',
                'location' => 'top-menu',
                'path' => 'add/resourcefile',
                'parent' => '0',
                'language' => 'pa',
                'weight' => '1',
                'tnid' => '131',
                'created_at' => '2020-03-25 22:37:39',
                'updated_at' => '2020-03-25 22:37:39',
            ],
            [
                'id' => '8450',
                'title' => 'Accessibility Statement',
                'location' => 'footer-menu',
                'path' => '/en/page/4138',
                'parent' => '0',
                'language' => 'en',
                'weight' => '5',
                'tnid' => '8414',
                'created_at' => '2021-09-21 23:53:37',
                'updated_at' => '2021-09-21 23:55:17',
            ],
            [
                'id' => '8451',
                'title' => 'در مورد دسترسی به مطالب کتاب‌خانه',
                'location' => 'footer-menu',
                'path' => '/fa/page/4139',
                'parent' => '0',
                'language' => 'fa',
                'weight' => '5',
                'tnid' => '8415',
                'created_at' => '2021-09-22 00:15:51',
                'updated_at' => '2021-09-27 11:53:24',
            ],
            [
                'id' => '8452',
                'title' => 'د لاسرسي بیانیه',
                'location' => 'footer-menu',
                'path' => '/ps/page/4140',
                'parent' => '0',
                'language' => 'ps',
                'weight' => '5',
                'tnid' => '8416',
                'created_at' => '2021-09-27 12:39:54',
                'updated_at' => '2021-10-04 23:27:37',
            ],
        ];

        DB::table('menus')->insert($data);
    }
}
