<?php

namespace Tests\Unit\Http\Requests;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\SubscribeRequest
 */
class SubscribeRequestTest extends TestCase
{
    /** @var \App\Http\Requests\SubscribeRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\SubscribeRequest();
    }

    /**
     * @test
     */
    public function authorize(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'g-recaptcha-response' => [
            ],
            'email' => [
                'required',
                'email',
                'unique:subscribers,email',
            ],
            'name' => [
                'required',
                'string',
            ],
        ], $actual);
    }

    // test cases...
}
