<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\AnalyticsController
 */
class AnalyticsControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/analytics');

        $response->assertOk();
        $response->assertViewIs('admin.analytics.analytics_main');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('analytics'), [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertViewIs('admin.analytics.user_gender');
        $response->assertViewHas('totalUsersByGender');

        // TODO: perform additional assertions
    }

    // test cases...
}
