<?php

namespace Tests\Feature\Http\Controllers;

use App\Models\Menu;
use App\Models\News;
use App\Models\Page;
use App\Models\Resource;
use App\Models\ResourceAttachment;
use App\Models\ResourceComment;
use App\Models\ResourceFavorite;
use App\Models\User;
use App\Models\UserProfile;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ApiController
 */
class ApiControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function delete_returns_an_ok_response(): void
    {
        $user = User::factory()->create();

        $userProfile = UserProfile::factory()->create(['user_id' => $user->id]);
        $response = $this->actingAs($user)->post('api/user/delete');

        $response->assertOk();

        $deletedUser = User::with('profile')->whereId($user->id)->first();

        $this->assertEquals('0', $deletedUser->status);
        $this->assertEquals(null, $deletedUser->profile->first_name);
        $this->assertEquals(null, $deletedUser->profile->last_name);
        $this->assertEquals(null, $deletedUser->profile->gender);
        $this->assertEquals(null, $deletedUser->profile->country);
        $this->assertEquals(null, $deletedUser->profile->city);
    }

    /**
     * @test
     */
    public function favorites_returns_an_ok_response(): void
    {
        $user = User::factory()->create();

        $resources = Resource::factory()->times(3)->create();

        foreach ($resources as $resource) {
            ResourceFavorite::factory()->create(['user_id' => $user->id, 'resource_id' => $resource->id]);
        }

        $response = $this->actingAs($user)->post('api/favorites');

        $response->assertOk();

        $responseData = $response->json();
        $this->assertCount(3, $responseData); // Should match the number of resources created

        foreach ($resources as $resource) {
            $this->assertTrue(in_array($resource->id, array_column($responseData, 'id')));
        }
    }

    /**
     * @test
     */
    public function featured_resources_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->getJson('api/featured_resources/{lang?}');

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function filter_resources_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->getJson('api/filter_resources/{lang?}');

        $response->assertOk();
        $response->assertViewIs('resources.resources_list_content');
        $response->assertViewHas('resources');
        $response->assertViewHas('views');
        $response->assertViewHas('favorites');
        $response->assertViewHas('comments');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_file_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $resourceAttachment = ResourceAttachment::factory()->create();

        $response = $this->getJson('api/resource/getFile/{fileId}');

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function get_file_aborts_with_a_404(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $resourceAttachment = ResourceAttachment::factory()->create();

        // TODO: perform additional setup to trigger `abort(404)`...

        $response = $this->getJson('api/resource/getFile/{fileId}');

        $response->assertNotFound();
    }

    /**
     * @test
     */
    public function links_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $menus = Menu::factory()->times(3)->create();

        $response = $this->getJson('api/links/{lang?}');

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function login_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = User::factory()->create();

        $response = $this->postJson('api/login', [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function logout_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->postJson('api/logout', [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function news_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $news = News::factory()->times(3)->create();

        $response = $this->getJson('api/news/{id}');

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function news_list_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $news = News::factory()->times(3)->create();

        $response = $this->getJson('api/news_list/{lang?}');

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function news_view_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $news = News::factory()->times(3)->create();

        $response = $this->getJson('api/news_view/{id}');

        $response->assertOk();
        $response->assertViewIs('news.news_api_view');
        $response->assertViewHas('news', $news);
        $response->assertViewHas('translations');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function page_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $pages = Page::factory()->times(3)->create();

        $response = $this->getJson('api/page/{id}');

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function page_view_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $page = Page::factory()->create();
        $pages = Page::factory()->times(3)->create();

        $response = $this->getJson('api/page_view/{id}');

        $response->assertOk();
        $response->assertViewIs('pages.page_app_view');
        $response->assertViewHas('page', $page);
        $response->assertViewHas('translations');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function pages_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $pages = Page::factory()->times(3)->create();

        $response = $this->getJson('api/pages/{lang?}');

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function register_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->postJson('api/register', [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function resource_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $resources = Resource::factory()->times(3)->create();

        $response = $this->getJson('api/resource/{id}');

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function resource_attributes_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $resource = Resource::factory()->create();
        $resourceComments = ResourceComment::factory()->times(3)->create();

        $response = $this->getJson('api/resource_attributes/{id}');

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function resource_categories_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->getJson('api/resource_categories/{lang?}');

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function resource_offset_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->getJson('api/resources/{lang}/{offset}');

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function resources_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $resources = Resource::factory()->times(3)->create();

        $response = $this->getJson('api/resources/{lang?}');

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function user_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->postJson('api/user', [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertJsonStructure([
            // TODO: compare expected response data
        ]);

        // TODO: perform additional assertions
    }

    // test cases...
}
