<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\CommentController
 */
class CommentControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function delete_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $resourceComment = \App\Models\ResourceComment::factory()->create();

        $response = $this->get('admin/comments/delete/{commentId}');

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $resourceComments = \App\Models\ResourceComment::factory()->times(3)->create();

        $response = $this->get('admin/comments');

        $response->assertOk();
        $response->assertViewIs('admin.comments.comments_list');
        $response->assertViewHas('comments');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function published_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $resourceComment = \App\Models\ResourceComment::factory()->create();

        $response = $this->get('admin/comments/published/{commentId}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
