<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ContactController
 */
class ContactControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('contact-us');

        $response->assertOk();
        $response->assertViewIs('contacts.contacts_view');
        $response->assertViewHas('email');
        $response->assertViewHas('fullname');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function delete_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $contact = \App\Models\Contact::factory()->create();

        $response = $this->get('admin/contacts/delete/{id}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $contacts = \App\Models\Contact::factory()->times(3)->create();

        $response = $this->get('admin/contacts');

        $response->assertOk();
        $response->assertViewIs('admin.contacts.contact_list');
        $response->assertViewHas('records');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function read_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $contact = \App\Models\Contact::factory()->create();

        $response = $this->get('admin/contacts/read/{id}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $setting = \App\Models\Setting::factory()->create();

        $response = $this->post(route('contact'), [
            // TODO: send request data
        ]);

        $response->assertRedirect('/contact-us');

        // TODO: perform additional assertions
    }

    // test cases...
}
