<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\DownloadController
 */
class DownloadControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $downloadCounts = \App\Models\DownloadCount::factory()->times(3)->create();

        $response = $this->get('admin/reports/downloads');

        $response->assertOk();
        $response->assertViewIs('admin.downloads.download_list');
        $response->assertViewHas('records');
        $response->assertViewHas('filters');

        // TODO: perform additional assertions
    }

    // test cases...
}
