<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\GlossaryAnalyticsController
 */
class GlossaryAnalyticsControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $devices = \App\Models\Device::factory()->times(3)->create();
        $browsers = \App\Models\Browser::factory()->times(3)->create();
        $platforms = \App\Models\Platform::factory()->times(3)->create();
        $glossarySubjects = \App\Models\GlossarySubject::factory()->times(3)->create();

        $response = $this->get('admin/analytics/glossary');

        $response->assertOk();
        $response->assertViewIs('admin.analytics.glossary.index');
        $response->assertViewHas('languages');
        $response->assertViewHas('genders');
        $response->assertViewHas('glossarySubjects', $glossarySubjects);
        $response->assertViewHas('devices', $devices);
        $response->assertViewHas('platforms', $platforms);
        $response->assertViewHas('browsers', $browsers);
        $response->assertViewHas('totalViews');
        $response->assertViewHas('totalRegisteredUsersViews');
        $response->assertViewHas('totalGuestViews');
        $response->assertViewHas('platformCounts');
        $response->assertViewHas('browserCounts');
        $response->assertViewHas('glossarySubjectCounts');
        $response->assertViewHas('totalViewsBasedOnLanguage');
        $response->assertViewHas('status');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function view_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $devices = \App\Models\Device::factory()->times(3)->create();
        $browsers = \App\Models\Browser::factory()->times(3)->create();
        $platforms = \App\Models\Platform::factory()->times(3)->create();
        $glossarySubjects = \App\Models\GlossarySubject::factory()->times(3)->create();

        $response = $this->get('admin/analytics/reports/glossary');

        $response->assertOk();
        $response->assertViewIs('admin.analytics.glossary.get-views');
        $response->assertViewHas(['views', 'glossarySubjects', 'languages', 'genders', 'devices', 'browsers', 'platforms']);

        // TODO: perform additional assertions
    }

    // test cases...
}
