<?php

namespace Tests\Feature\Http\Controllers;

use App\Models\Menu;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\MenuController
 */
class MenuControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function ajax_get_parents_returns_an_ok_response(): void
    {
        $this->refreshApplicationWithLocale('en');

        $admin = User::factory()->create();
        $admin->roles()->attach(5);

        $menus = Menu::factory()->count(3)->create();

        $response = $this->actingAs($admin)->get(route('ajax_get_parents', ['id' => $menus[0]->id, 'loc' => $menus[0]->location, 'lang' => 'en']));

        $response->assertOk();

    }

    /**
     * @test
     */
    public function create_returns_an_ok_response(): void
    {
        $this->refreshApplicationWithLocale('en');

        $admin = User::factory()->create();
        $admin->roles()->attach(5);

        $response = $this->actingAs($admin)->get('en/admin/menu/add/0'); // Assuming 0 for new menu

        $response->assertOk();
        $response->assertViewIs('admin.menu.menu_add');
        $response->assertViewHas('menu');
        $response->assertViewHas('new_menu', true);
        $response->assertViewHas('locations');
        $response->assertViewHas('parents');
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response(): void
    {
        $this->refreshApplicationWithLocale('en');

        $admin = User::factory()->create();
        $admin->roles()->attach(5);

        $menu = Menu::factory()->create();

        $response = $this->actingAs($admin)->get('en/admin/menu/edit/' . $menu->id);

        $response->assertOk();
        $response->assertViewIs('admin.menu.menu_edit');
        $response->assertViewHas('details');
        $response->assertViewHas('locations');
        $response->assertViewHas('parents');
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->refreshApplicationWithLocale('en');

        $admin = User::factory()->create();
        $admin->roles()->attach(5);

        $menus = Menu::factory()->count(3)->create();

        $response = $this->actingAs($admin)->get('en/admin/menu');

        $response->assertOk();
        $response->assertViewIs('admin.menu.menu_list');
        $response->assertViewHas('menuRecords');
        $response->assertViewHas('searchBar');
        $this->assertCount(3, $response->viewData('menuRecords'));
    }

    /**
     * @test
     */
    public function sort_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $menu = \App\Models\Menu::factory()->create();

        $response = $this->get(route('sort_menu'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('store_menu'), [
            // TODO: send request data
        ]);

        $response->assertRedirect('admin/menu');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_aborts_with_a_400(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        // TODO: perform additional setup to trigger `abort(400)`...

        $response = $this->post(route('store_menu'), [
            // TODO: send request data
        ]);

        $response->assertStatus(400);
    }

    /**
     * @test
     */
    public function translate_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $menu = \App\Models\Menu::factory()->create();
        $menus = \App\Models\Menu::factory()->times(3)->create();

        $response = $this->get('admin/menu/translate/{menuId}');

        $response->assertOk();
        $response->assertViewIs('admin.menu.menu_translate');
        $response->assertViewHas('translations');
        $response->assertViewHas('locals');
        $response->assertViewHas('tnid');
        $response->assertViewHas('id');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $menu = \App\Models\Menu::factory()->create();

        $response = $this->post(route('update_menu', ['menuId' => $menu->menuId]), [
            // TODO: send request data
        ]);

        $response->assertRedirect('admin/menu/edit/'.$menuId);

        // TODO: perform additional assertions
    }

    // test cases...
}
