<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\ResourceAnalyticsController
 */
class ResourceAnalyticsControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $taxonomyTerms = \App\Models\TaxonomyTerm::factory()->times(3)->create();

        $response = $this->get('admin/analytics/resource');

        $response->assertOk();
        $response->assertViewIs('admin.analytics.resource-analytics.index');
        $response->assertViewHas(['genders', 'languages', 'totalResources', 'sumOfAllIndividualDownloadedFileSizes', 'top10Authors', 'top10Publishers', 'top10DownloadedResources', 'top10DownloadedResourcesByFileSizes', 'top10FavoriteResources', 'subjectAreas', 'resourceTypes']);

        // TODO: perform additional assertions
    }

    // test cases...
}
