<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\SurveyAnswerController
 */
class SurveyAnswerControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function all_questions_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $surveyQuestions = \App\Models\SurveyQuestion::factory()->times(3)->create();

        $response = $this->get('admin/survey_questions');

        $response->assertOk();
        $response->assertViewIs('admin.surveys.result.view');
        $response->assertViewHas('survey_questions');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function question_answers_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $surveyQuestion = \App\Models\SurveyQuestion::factory()->create();
        $surveyAnswer = \App\Models\SurveyAnswer::factory()->create();
        $surveyAnswers = \App\Models\SurveyAnswer::factory()->times(3)->create();

        $response = $this->get('admin/survey_question/answers/{id}');

        $response->assertOk();
        $response->assertViewIs('admin.surveys.result.result');
        $response->assertViewHas('question');
        $response->assertViewHas('survey_question_options');
        $response->assertViewHas('descriptive_answers');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_user_survey_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $surveyQuestion = \App\Models\SurveyQuestion::factory()->create();
        $surveyQuestionOption = \App\Models\SurveyQuestionOption::factory()->create();

        $response = $this->post(route('survey'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
