<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\SurveyController
 */
class SurveyControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function add_translate_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $survey = \App\Models\Survey::factory()->create();

        $response = $this->get('admin/survey/add/translate/{id}/{lang}');

        $response->assertOk();
        $response->assertViewIs('admin.surveys.survey.add_translation');
        $response->assertViewHas('tnid');
        $response->assertViewHas('lang');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function create_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/survey/create');

        $response->assertOk();
        $response->assertViewIs('admin.surveys.survey.create');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function delete_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $survey = \App\Models\Survey::factory()->create();

        $response = $this->get('admin/survey/delete/{id}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $survey = \App\Models\Survey::factory()->create();

        $response = $this->get('admin/survey/edit/{id}');

        $response->assertOk();
        $response->assertViewIs('admin.surveys.survey.edit');
        $response->assertViewHas('survey', $survey);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $surveys = \App\Models\Survey::factory()->times(3)->create();

        $response = $this->get('admin/surveys');

        $response->assertOk();
        $response->assertViewIs('admin.surveys.survey.list');
        $response->assertViewHas('surveys', $surveys);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function report_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $survey = \App\Models\Survey::factory()->create();
        $surveyQuestions = \App\Models\SurveyQuestion::factory()->times(3)->create();

        $response = $this->get('admin/survey/report/{id}');

        $response->assertOk();
        $response->assertViewIs('admin.surveys.survey.report');
        $response->assertViewHas('survey', $survey);
        $response->assertViewHas('survey_questions');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $survey = \App\Models\Survey::factory()->create();

        $response = $this->post(route('create_survey'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $survey = \App\Models\Survey::factory()->create();

        $response = $this->post(route('update_survey', ['id' => $survey->id]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function view_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $survey = \App\Models\Survey::factory()->create();

        $response = $this->get('admin/survey/view/{id}/{tnid}');

        $response->assertOk();
        $response->assertViewIs('admin.surveys.survey.view');
        $response->assertViewHas('surveys');
        $response->assertViewHas('survey_self');

        // TODO: perform additional assertions
    }

    // test cases...
}
