<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\SurveyQuestionOptionController
 */
class SurveyQuestionOptionControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function add_translate_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $surveyQuestionOption = \App\Models\SurveyQuestionOption::factory()->create();
        $surveyQuestion = \App\Models\SurveyQuestion::factory()->create();
        $survey = \App\Models\Survey::factory()->create();

        $response = $this->get('admin/survey/question/option/add/translate/{id}/{lang}');

        $response->assertOk();
        $response->assertViewIs('admin.surveys.option.add_translation');
        $response->assertViewHas('tnid');
        $response->assertViewHas('lang');
        $response->assertViewHas('question');
        $response->assertViewHas('survey', $survey);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function create_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $survey = \App\Models\Survey::factory()->create();
        $surveyQuestion = \App\Models\SurveyQuestion::factory()->create();
        $surveyQuestionOption = \App\Models\SurveyQuestionOption::factory()->create();

        $response = $this->get('admin/survey/{survey_id}/question/{id}/option/create');

        $response->assertOk();
        $response->assertViewIs('admin.surveys.option.create');
        $response->assertViewHas('survey', $survey);
        $response->assertViewHas('question');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function delete_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $surveyQuestionOption = \App\Models\SurveyQuestionOption::factory()->create();

        $response = $this->get('admin/survey/question/option/delete/{id}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $surveyQuestion = \App\Models\SurveyQuestion::factory()->create();
        $surveyQuestionOption = \App\Models\SurveyQuestionOption::factory()->create();
        $surveyQuestions = \App\Models\SurveyQuestion::factory()->times(3)->create();
        $surveyQuestionOptions = \App\Models\SurveyQuestionOption::factory()->times(3)->create();

        $response = $this->get('admin/survey/{survey_id}/question/{id}/view_options');

        $response->assertOk();
        $response->assertViewIs('admin.surveys.option.list');
        $response->assertViewHas('question_self');
        $response->assertViewHas('questin_options');
        $response->assertViewHas('survey');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $surveyQuestionOption = \App\Models\SurveyQuestionOption::factory()->create();

        $response = $this->post(route('create_option'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function view_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $surveyQuestionOption = \App\Models\SurveyQuestionOption::factory()->create();
        $surveyQuestion = \App\Models\SurveyQuestion::factory()->create();
        $survey = \App\Models\Survey::factory()->create();

        $response = $this->get('admin/survey/question/{questionid}/option/{optionid}/view/{tnid}');

        $response->assertOk();
        $response->assertViewIs('admin.surveys.option.view');
        $response->assertViewHas('options');
        $response->assertViewHas('option_self');
        $response->assertViewHas('question');
        $response->assertViewHas('survey', $survey);

        // TODO: perform additional assertions
    }

    // test cases...
}
