<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\SyncController
 */
class SyncControllerTest extends TestCase
{
    /**
     * @test
     */
    public function sync_it_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/run_sync');

        $response->assertRedirect('admin/sync');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/sync');

        $response->assertOk();
        $response->assertViewIs('admin.sync.sync_status');
        $response->assertViewHas('countResourceRecords');
        $response->assertViewHas('countDdlFileRecords');
        $response->assertViewHas('countNewsRecords');
        $response->assertViewHas('countPageRecords');
        $response->assertViewHas('countTaxonomyTermRecords');

        // TODO: perform additional assertions
    }

    // test cases...
}
