<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\UserAnalyticsController
 */
class UserAnalyticsControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get('admin/analytics/user');

        $response->assertOk();
        $response->assertViewIs('admin.analytics.users.index');
        $response->assertViewHas(['roles', 'totalUsersBaseOnGenders', 'top10ActiveUsers', 'totalRegisteredUsers', 'totalUsers', 'totalGoogleUsers', 'totalFacebookUsers']);

        // TODO: perform additional assertions
    }

    // test cases...
}
