<?php

namespace Tests\Feature\Http\Controllers\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\SubscriberController
 */
class SubscriberControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function destroy_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $subscriber = \App\Models\Subscriber::factory()->create();

        $response = $this->delete(route('subscribers.destroy', [$subscriber]));

        $response->assertOk();
        $this->assertModelMissing($subscriber);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response(): void
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('subscribers.index'));

        $response->assertOk();
        $response->assertViewIs('admin.subscriber.index');
        $response->assertViewHas('subscribers');
        $response->assertViewHas('totalSubscribers');

        // TODO: perform additional assertions
    }

    // test cases...
}
